### ISSUE TITLE
Environment.stat ?

### ISSUE THREAD

**Issue by greenersharp** [capocasa/limdb#5]
First off, thanks for the great library.  

In Python's LMDB library there is a handy `stat()` method that returns the statistics for the database, most importantly, the `entries` field which tells us how many records are in the database.

In python:
https://lmdb.readthedocs.io/en/release/#storage-efficiency-limits

```
>>> pprint(env.stat())
{'branch_pages': 1040L,
 'depth': 4L,
 'entries': 3761848L,
 'leaf_pages': 73658L,
 'overflow_pages': 0L,
 'psize': 4096L}
```

The entries # is very handy for times when I need to walk thru a large database; knowing the total lets me use Tqdm (or Suru in Nim) that shows a progress bar.

I'm not sure if I missed it in the docs, but does Limdb expose this information?

Thanks again.

**Comment by capocasa** [comment]
Good to know!!! No, not directly. You can open a transaction and get the information like so:

db.withTransation t:
  stat(t.txn, t.dbi)

It wouldn't be hard to include it- if you can, of course I would love a patch to add this feature to the library. Check out the 'len' proc for an example.
